SELECT COUNT(DISTINCT DEPT_NO)
FROM DEPT_EMP;

SELECT DISTINCT DEPT_NO
FROM DEPT_EMP;

SELECT SUM(SALARY)
FROM SALARIES;

SELECT COUNT(DISTINCT SALARY)
FROM SALARIES;

SELECT SUM(SALARY)
FROM SALARIES
WHERE FROM_DATE > '1997-01-01';

SELECT MAX(SALARY)
FROM SALARIES;

SELECT MIN(SALARY)
FROM SALARIES;

SELECT MAX(EMP_NO)
FROM EMPLOYEES;

SELECT MIN(EMP_NO)
FROM EMPLOYEES;

SELECT AVG(SALARY)
FROM SALARIES
WHERE (FROM_DATE) > '1997-01-01';

SELECT ROUND(AVG(SALARY), 2)
FROM SALARIES
WHERE (FROM_DATE) > '1997-01-01';

SELECT * FROM DEPARTMENTS_DUP;

SELECT DEPT_NO,
IFNULL(DEPT_NAME, 'Dept name not provided') AS DEPT_NAME
FROM DEPARTMENTS_DUP
ORDER BY DEPT_NO;

SELECT DEPT_NO, DEPT_NAME,
COALESCE(DEPT_MANAGER,DEPT_NAME, 'Dept name not provided') AS DEPT_MANAGER
FROM DEPARTMENTS_DUP;

USE EMPLOYEES;
SELECT DEPT_NO, DEPT_NAME,
COALESCE(DEPT_NO,DEPT_NAME,'DEPT_NAME') AS DEPT_INFO
FROM DEPARTMENTS_DUP
ORDER BY DEPT_NO;

SELECT DEPT_NO, DEPT_NAME,
COALESCE(DEPT_NAME,'DEPT_NAME') AS DEPT_INFO
FROM DEPARTMENTS_DUP
ORDER BY DEPT_NO;

SELECT DEPT_NO,DEPT_NAME,
IFNULL(DEPT_NO,'N/A') AS DEPT_NO,
IFNULL(DEPT_NAME,'Department name not provided') AS DEPT_NAME,
COALESCE(DEPT_NO, DEPT_NAME) AS DEPT_INFO
FROM DEPARTMENTS_DUP
ORDER BY DEPT_NO;

